version: '3.6'

services:
  nfs-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    privileged: true
    volumes:
      - ./testdata/nfs/:/data/nfs/
      - ./testdata/log:/log
    environment:
      - SHARED_DIRECTORY_1="/data/nfs"
      - MOUNT_SETTINGS_1="*(rw,fsid=0,async,subtree_check,no_auth_nlm,insecure,no_root_squash)"
