#!/command/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# mountd
# Run the NFS server daemon
# ==============================================================================

echo "Mounting nfsd..." | info

mount -a

echo "Starting mountd..." | info

# shellcheck disable=SC2086
exec \
    fdmove -c 2 1 \
      /usr/sbin/rpc.mountd \
        --foreground \
        --debug all \
        ${MOUNTD_ARGUMENTS}
