#!/command/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# rpcbind
# Run rpcbind
# ==============================================================================

echo "Starting rpcbind..." | info
while true; do
    sleep 1
done
#exec \
#    fdmove -c 2 1 \
#      /sbin/rpcbind -f
