#!/command/with-contenv sh
. "/usr/local/bin/logger"
# ==============================================================================
# nfsd
# Start the NFS server process
# ==============================================================================

echo "Starting nfsd..." | info

# shellcheck disable=SC2086
exec \
    fdmove -c 2 1 \
      /usr/sbin/rpc.nfsd \
        ${NFSD_ARGUMENTS}
